spring.application.name=JWS-SS6-MiniProject
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mini_project_ss6?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name=doj9thlet
cloudinary.api-key=562728421816383
cloudinary.api-secret=oKrtakqNa1w0IJWTlQrJIAhXMDI